// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package ds.examples.transfer;

public interface DeductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transfer.DeductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float deductAmount = 1;</code>
   */
  float getDeductAmount();
}
