// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package ds.examples.transfer;

public interface DeductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transfer.DeductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float deductTotal = 1;</code>
   */
  float getDeductTotal();
}
