// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package ds.examples.transfer;

public interface DepositResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transfer.DepositResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float depositTotal = 1;</code>
   */
  float getDepositTotal();
}
