// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package ds.examples.transfer;

public interface DepositRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transfer.DepositRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float depositAmount = 1;</code>
   */
  float getDepositAmount();
}
