// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package ds.examples.transfer;

public interface SavingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transfer.SavingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float savingTotal = 1;</code>
   */
  float getSavingTotal();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
