// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package ds.examples.transfer;

public interface SavingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transfer.SavingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool viewSaving = 1;</code>
   */
  boolean getViewSaving();
}
