// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package ds.examples.transfer;

public final class TransferServiceImpl {
  private TransferServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transfer_DepositRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transfer_DepositRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transfer_DepositResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transfer_DepositResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transfer_DeductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transfer_DeductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transfer_DeductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transfer_DeductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016transfer.proto\022\010transfer\"\'\n\016DepositReq" +
      "uest\022\025\n\rdepositAmount\030\001 \001(\002\"\'\n\017DepositRe" +
      "sponse\022\024\n\014depositTotal\030\001 \001(\002\"%\n\rDeductRe" +
      "quest\022\024\n\014deductAmount\030\001 \001(\002\"%\n\016DeductRes" +
      "ponse\022\023\n\013deductTotal\030\001 \001(\0022\242\001\n\017TransferS" +
      "ervice\022G\n\014depositFunds\022\030.transfer.Deposi" +
      "tRequest\032\031.transfer.DepositResponse\"\000(\001\022" +
      "F\n\013deductFunds\022\027.transfer.DeductRequest\032" +
      "\030.transfer.DeductResponse\"\000(\0010\001B-\n\024ds.ex" +
      "amples.transferB\023TransferServiceImplP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_transfer_DepositRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transfer_DepositRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transfer_DepositRequest_descriptor,
        new java.lang.String[] { "DepositAmount", });
    internal_static_transfer_DepositResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_transfer_DepositResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transfer_DepositResponse_descriptor,
        new java.lang.String[] { "DepositTotal", });
    internal_static_transfer_DeductRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_transfer_DeductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transfer_DeductRequest_descriptor,
        new java.lang.String[] { "DeductAmount", });
    internal_static_transfer_DeductResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_transfer_DeductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transfer_DeductResponse_descriptor,
        new java.lang.String[] { "DeductTotal", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
