// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package ds.examples.transfer;

public final class TransferServiceImpl {
  private TransferServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transfer_DepositRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transfer_DepositRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transfer_DepositResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transfer_DepositResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transfer_DeductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transfer_DeductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transfer_DeductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transfer_DeductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transfer_SavingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transfer_SavingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transfer_SavingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transfer_SavingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016transfer.proto\022\010transfer\"\'\n\016DepositReq" +
      "uest\022\025\n\rdepositAmount\030\001 \001(\002\"\'\n\017DepositRe" +
      "sponse\022\024\n\014depositTotal\030\001 \001(\002\"%\n\rDeductRe" +
      "quest\022\024\n\014deductAmount\030\001 \001(\002\"%\n\016DeductRes" +
      "ponse\022\023\n\013deductTotal\030\001 \001(\002\"#\n\rSavingRequ" +
      "est\022\022\n\nviewSaving\030\001 \001(\010\"6\n\016SavingRespons" +
      "e\022\023\n\013savingTotal\030\001 \001(\002\022\017\n\007message\030\002 \001(\t2" +
      "\346\001\n\017TransferService\022G\n\014depositFunds\022\030.tr" +
      "ansfer.DepositRequest\032\031.transfer.Deposit" +
      "Response\"\000(\001\022F\n\013deductFunds\022\027.transfer.D" +
      "eductRequest\032\030.transfer.DeductResponse\"\000" +
      "(\0010\001\022B\n\013savingsFund\022\027.transfer.SavingReq" +
      "uest\032\030.transfer.SavingResponse\"\000B-\n\024ds.e" +
      "xamples.transferB\023TransferServiceImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_transfer_DepositRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transfer_DepositRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transfer_DepositRequest_descriptor,
        new java.lang.String[] { "DepositAmount", });
    internal_static_transfer_DepositResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_transfer_DepositResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transfer_DepositResponse_descriptor,
        new java.lang.String[] { "DepositTotal", });
    internal_static_transfer_DeductRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_transfer_DeductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transfer_DeductRequest_descriptor,
        new java.lang.String[] { "DeductAmount", });
    internal_static_transfer_DeductResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_transfer_DeductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transfer_DeductResponse_descriptor,
        new java.lang.String[] { "DeductTotal", });
    internal_static_transfer_SavingRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_transfer_SavingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transfer_SavingRequest_descriptor,
        new java.lang.String[] { "ViewSaving", });
    internal_static_transfer_SavingResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_transfer_SavingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transfer_SavingResponse_descriptor,
        new java.lang.String[] { "SavingTotal", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
