// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: view.proto

package ds.examples.views;

public interface AccountNameResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:views.AccountNameResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accName = 1;</code>
   */
  java.lang.String getAccName();
  /**
   * <code>string accName = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccNameBytes();
}
