// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: view.proto

package ds.examples.views;

public interface AccountNameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:views.AccountNameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 accId = 1;</code>
   */
  int getAccId();
}
