// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: view.proto

package ds.examples.views;

public interface ContactsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:views.ContactsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 contactId = 1;</code>
   */
  int getContactId();
}
