// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: view.proto

package ds.examples.views;

/**
 * <pre>
 * client -&gt; id 1 -&gt;  server -&gt; Mark 1, Jon 2, Paddy 3,
 * </pre>
 *
 * Protobuf type {@code views.ContactsResponse}
 */
public  final class ContactsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:views.ContactsResponse)
    ContactsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContactsResponse.newBuilder() to construct.
  private ContactsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContactsResponse() {
    accContacts_ = "";
    contactNum_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ContactsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            accContacts_ = s;
            break;
          }
          case 16: {

            contactNum_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.examples.views.ViewServiceImpl.internal_static_views_ContactsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.examples.views.ViewServiceImpl.internal_static_views_ContactsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.examples.views.ContactsResponse.class, ds.examples.views.ContactsResponse.Builder.class);
  }

  public static final int ACCCONTACTS_FIELD_NUMBER = 1;
  private volatile java.lang.Object accContacts_;
  /**
   * <code>string accContacts = 1;</code>
   */
  public java.lang.String getAccContacts() {
    java.lang.Object ref = accContacts_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accContacts_ = s;
      return s;
    }
  }
  /**
   * <code>string accContacts = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAccContactsBytes() {
    java.lang.Object ref = accContacts_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accContacts_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTACTNUM_FIELD_NUMBER = 2;
  private int contactNum_;
  /**
   * <code>int32 contactNum = 2;</code>
   */
  public int getContactNum() {
    return contactNum_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAccContactsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accContacts_);
    }
    if (contactNum_ != 0) {
      output.writeInt32(2, contactNum_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAccContactsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accContacts_);
    }
    if (contactNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, contactNum_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.examples.views.ContactsResponse)) {
      return super.equals(obj);
    }
    ds.examples.views.ContactsResponse other = (ds.examples.views.ContactsResponse) obj;

    boolean result = true;
    result = result && getAccContacts()
        .equals(other.getAccContacts());
    result = result && (getContactNum()
        == other.getContactNum());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCCONTACTS_FIELD_NUMBER;
    hash = (53 * hash) + getAccContacts().hashCode();
    hash = (37 * hash) + CONTACTNUM_FIELD_NUMBER;
    hash = (53 * hash) + getContactNum();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.examples.views.ContactsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.examples.views.ContactsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.examples.views.ContactsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.examples.views.ContactsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.examples.views.ContactsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.examples.views.ContactsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.examples.views.ContactsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.examples.views.ContactsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.examples.views.ContactsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.examples.views.ContactsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.examples.views.ContactsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.examples.views.ContactsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.examples.views.ContactsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * client -&gt; id 1 -&gt;  server -&gt; Mark 1, Jon 2, Paddy 3,
   * </pre>
   *
   * Protobuf type {@code views.ContactsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:views.ContactsResponse)
      ds.examples.views.ContactsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.examples.views.ViewServiceImpl.internal_static_views_ContactsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.examples.views.ViewServiceImpl.internal_static_views_ContactsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.examples.views.ContactsResponse.class, ds.examples.views.ContactsResponse.Builder.class);
    }

    // Construct using ds.examples.views.ContactsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      accContacts_ = "";

      contactNum_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.examples.views.ViewServiceImpl.internal_static_views_ContactsResponse_descriptor;
    }

    @java.lang.Override
    public ds.examples.views.ContactsResponse getDefaultInstanceForType() {
      return ds.examples.views.ContactsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.examples.views.ContactsResponse build() {
      ds.examples.views.ContactsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.examples.views.ContactsResponse buildPartial() {
      ds.examples.views.ContactsResponse result = new ds.examples.views.ContactsResponse(this);
      result.accContacts_ = accContacts_;
      result.contactNum_ = contactNum_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.examples.views.ContactsResponse) {
        return mergeFrom((ds.examples.views.ContactsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.examples.views.ContactsResponse other) {
      if (other == ds.examples.views.ContactsResponse.getDefaultInstance()) return this;
      if (!other.getAccContacts().isEmpty()) {
        accContacts_ = other.accContacts_;
        onChanged();
      }
      if (other.getContactNum() != 0) {
        setContactNum(other.getContactNum());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.examples.views.ContactsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.examples.views.ContactsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object accContacts_ = "";
    /**
     * <code>string accContacts = 1;</code>
     */
    public java.lang.String getAccContacts() {
      java.lang.Object ref = accContacts_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accContacts_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string accContacts = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccContactsBytes() {
      java.lang.Object ref = accContacts_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accContacts_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accContacts = 1;</code>
     */
    public Builder setAccContacts(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accContacts_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string accContacts = 1;</code>
     */
    public Builder clearAccContacts() {
      
      accContacts_ = getDefaultInstance().getAccContacts();
      onChanged();
      return this;
    }
    /**
     * <code>string accContacts = 1;</code>
     */
    public Builder setAccContactsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accContacts_ = value;
      onChanged();
      return this;
    }

    private int contactNum_ ;
    /**
     * <code>int32 contactNum = 2;</code>
     */
    public int getContactNum() {
      return contactNum_;
    }
    /**
     * <code>int32 contactNum = 2;</code>
     */
    public Builder setContactNum(int value) {
      
      contactNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 contactNum = 2;</code>
     */
    public Builder clearContactNum() {
      
      contactNum_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:views.ContactsResponse)
  }

  // @@protoc_insertion_point(class_scope:views.ContactsResponse)
  private static final ds.examples.views.ContactsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.examples.views.ContactsResponse();
  }

  public static ds.examples.views.ContactsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContactsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ContactsResponse>() {
    @java.lang.Override
    public ContactsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ContactsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ContactsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ContactsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.examples.views.ContactsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

