// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: view.proto

package ds.examples.views;

public interface ContactsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:views.ContactsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accContacts = 1;</code>
   */
  java.lang.String getAccContacts();
  /**
   * <code>string accContacts = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccContactsBytes();

  /**
   * <code>int32 contactNum = 2;</code>
   */
  int getContactNum();
}
