// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: view.proto

package ds.examples.views;

public final class ViewServiceImpl {
  private ViewServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_views_AccountNameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_views_AccountNameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_views_AccountNameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_views_AccountNameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_views_ContactsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_views_ContactsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_views_ContactsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_views_ContactsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nview.proto\022\005views\"#\n\022AccountNameReques" +
      "t\022\r\n\005accId\030\001 \001(\005\"&\n\023AccountNameResponse\022" +
      "\017\n\007accName\030\001 \001(\t\"$\n\017ContactsRequest\022\021\n\tc" +
      "ontactId\030\001 \001(\005\";\n\020ContactsResponse\022\023\n\013ac" +
      "cContacts\030\001 \001(\t\022\022\n\ncontactNum\030\002 \001(\0052\235\001\n\013" +
      "ViewService\022F\n\013accountName\022\031.views.Accou" +
      "ntNameRequest\032\032.views.AccountNameRespons" +
      "e\"\000\022F\n\017accountContacts\022\026.views.ContactsR" +
      "equest\032\027.views.ContactsResponse\"\0000\001B&\n\021d" +
      "s.examples.viewsB\017ViewServiceImplP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_views_AccountNameRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_views_AccountNameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_views_AccountNameRequest_descriptor,
        new java.lang.String[] { "AccId", });
    internal_static_views_AccountNameResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_views_AccountNameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_views_AccountNameResponse_descriptor,
        new java.lang.String[] { "AccName", });
    internal_static_views_ContactsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_views_ContactsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_views_ContactsRequest_descriptor,
        new java.lang.String[] { "ContactId", });
    internal_static_views_ContactsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_views_ContactsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_views_ContactsResponse_descriptor,
        new java.lang.String[] { "AccContacts", "ContactNum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
