// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: view.proto

package ds.examples.view;

public interface AccountNameResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:view.AccountNameResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accName = 1;</code>
   */
  java.lang.String getAccName();
  /**
   * <code>string accName = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccNameBytes();

  /**
   * <code>int32 accAge = 2;</code>
   */
  int getAccAge();
}
