// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: view.proto

package ds.examples.view;

public interface ContactsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:view.ContactsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string contactDetails = 1;</code>
   */
  java.lang.String getContactDetails();
  /**
   * <code>string contactDetails = 1;</code>
   */
  com.google.protobuf.ByteString
      getContactDetailsBytes();

  /**
   * <code>int32 contactId = 2;</code>
   */
  int getContactId();
}
