// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: view.proto

package ds.examples.view;

public interface ContactsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:view.ContactsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 contactGroup = 1;</code>
   */
  int getContactGroup();
}
