// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: view.proto

package ds.examples.view;

/**
 * <pre>
 *client -&gt; 3 -&gt;  server -&gt; Contact name: Mark gaffney id: 32, -&gt; so on Jon B 32, Jon B 32 id 2,
 * </pre>
 *
 * Protobuf type {@code view.ContactsResponse}
 */
public  final class ContactsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:view.ContactsResponse)
    ContactsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContactsResponse.newBuilder() to construct.
  private ContactsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContactsResponse() {
    contactDetails_ = "";
    contactId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ContactsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            contactDetails_ = s;
            break;
          }
          case 16: {

            contactId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.examples.view.ViewServiceImpl.internal_static_view_ContactsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.examples.view.ViewServiceImpl.internal_static_view_ContactsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.examples.view.ContactsResponse.class, ds.examples.view.ContactsResponse.Builder.class);
  }

  public static final int CONTACTDETAILS_FIELD_NUMBER = 1;
  private volatile java.lang.Object contactDetails_;
  /**
   * <code>string contactDetails = 1;</code>
   */
  public java.lang.String getContactDetails() {
    java.lang.Object ref = contactDetails_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contactDetails_ = s;
      return s;
    }
  }
  /**
   * <code>string contactDetails = 1;</code>
   */
  public com.google.protobuf.ByteString
      getContactDetailsBytes() {
    java.lang.Object ref = contactDetails_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contactDetails_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTACTID_FIELD_NUMBER = 2;
  private int contactId_;
  /**
   * <code>int32 contactId = 2;</code>
   */
  public int getContactId() {
    return contactId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getContactDetailsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contactDetails_);
    }
    if (contactId_ != 0) {
      output.writeInt32(2, contactId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getContactDetailsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, contactDetails_);
    }
    if (contactId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, contactId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.examples.view.ContactsResponse)) {
      return super.equals(obj);
    }
    ds.examples.view.ContactsResponse other = (ds.examples.view.ContactsResponse) obj;

    boolean result = true;
    result = result && getContactDetails()
        .equals(other.getContactDetails());
    result = result && (getContactId()
        == other.getContactId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTACTDETAILS_FIELD_NUMBER;
    hash = (53 * hash) + getContactDetails().hashCode();
    hash = (37 * hash) + CONTACTID_FIELD_NUMBER;
    hash = (53 * hash) + getContactId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.examples.view.ContactsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.examples.view.ContactsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.examples.view.ContactsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.examples.view.ContactsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.examples.view.ContactsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.examples.view.ContactsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.examples.view.ContactsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.examples.view.ContactsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.examples.view.ContactsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.examples.view.ContactsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.examples.view.ContactsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.examples.view.ContactsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.examples.view.ContactsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *client -&gt; 3 -&gt;  server -&gt; Contact name: Mark gaffney id: 32, -&gt; so on Jon B 32, Jon B 32 id 2,
   * </pre>
   *
   * Protobuf type {@code view.ContactsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:view.ContactsResponse)
      ds.examples.view.ContactsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.examples.view.ViewServiceImpl.internal_static_view_ContactsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.examples.view.ViewServiceImpl.internal_static_view_ContactsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.examples.view.ContactsResponse.class, ds.examples.view.ContactsResponse.Builder.class);
    }

    // Construct using ds.examples.view.ContactsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      contactDetails_ = "";

      contactId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.examples.view.ViewServiceImpl.internal_static_view_ContactsResponse_descriptor;
    }

    @java.lang.Override
    public ds.examples.view.ContactsResponse getDefaultInstanceForType() {
      return ds.examples.view.ContactsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.examples.view.ContactsResponse build() {
      ds.examples.view.ContactsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.examples.view.ContactsResponse buildPartial() {
      ds.examples.view.ContactsResponse result = new ds.examples.view.ContactsResponse(this);
      result.contactDetails_ = contactDetails_;
      result.contactId_ = contactId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.examples.view.ContactsResponse) {
        return mergeFrom((ds.examples.view.ContactsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.examples.view.ContactsResponse other) {
      if (other == ds.examples.view.ContactsResponse.getDefaultInstance()) return this;
      if (!other.getContactDetails().isEmpty()) {
        contactDetails_ = other.contactDetails_;
        onChanged();
      }
      if (other.getContactId() != 0) {
        setContactId(other.getContactId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.examples.view.ContactsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.examples.view.ContactsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object contactDetails_ = "";
    /**
     * <code>string contactDetails = 1;</code>
     */
    public java.lang.String getContactDetails() {
      java.lang.Object ref = contactDetails_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contactDetails_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contactDetails = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContactDetailsBytes() {
      java.lang.Object ref = contactDetails_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contactDetails_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contactDetails = 1;</code>
     */
    public Builder setContactDetails(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contactDetails_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contactDetails = 1;</code>
     */
    public Builder clearContactDetails() {
      
      contactDetails_ = getDefaultInstance().getContactDetails();
      onChanged();
      return this;
    }
    /**
     * <code>string contactDetails = 1;</code>
     */
    public Builder setContactDetailsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contactDetails_ = value;
      onChanged();
      return this;
    }

    private int contactId_ ;
    /**
     * <code>int32 contactId = 2;</code>
     */
    public int getContactId() {
      return contactId_;
    }
    /**
     * <code>int32 contactId = 2;</code>
     */
    public Builder setContactId(int value) {
      
      contactId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 contactId = 2;</code>
     */
    public Builder clearContactId() {
      
      contactId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:view.ContactsResponse)
  }

  // @@protoc_insertion_point(class_scope:view.ContactsResponse)
  private static final ds.examples.view.ContactsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.examples.view.ContactsResponse();
  }

  public static ds.examples.view.ContactsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContactsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ContactsResponse>() {
    @java.lang.Override
    public ContactsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ContactsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ContactsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ContactsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.examples.view.ContactsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

