// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: view.proto

package ds.examples.view;

public final class ViewServiceImpl {
  private ViewServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_view_AccountNameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_view_AccountNameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_view_AccountNameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_view_AccountNameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_view_ContactsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_view_ContactsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_view_ContactsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_view_ContactsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nview.proto\022\004view\"#\n\022AccountNameRequest" +
      "\022\r\n\005accId\030\001 \001(\005\"6\n\023AccountNameResponse\022\017" +
      "\n\007accName\030\001 \001(\t\022\016\n\006accAge\030\002 \001(\005\"\'\n\017Conta" +
      "ctsRequest\022\024\n\014contactGroup\030\001 \001(\005\"=\n\020Cont" +
      "actsResponse\022\026\n\016contactDetails\030\001 \001(\t\022\021\n\t" +
      "contactId\030\002 \001(\0052\226\001\n\013ViewService\022D\n\013accou" +
      "ntName\022\030.view.AccountNameRequest\032\031.view." +
      "AccountNameResponse\"\000\022A\n\014viewContacts\022\025." +
      "view.ContactsRequest\032\026.view.ContactsResp" +
      "onse\"\0000\001B%\n\020ds.examples.viewB\017ViewServic" +
      "eImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_view_AccountNameRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_view_AccountNameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_view_AccountNameRequest_descriptor,
        new java.lang.String[] { "AccId", });
    internal_static_view_AccountNameResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_view_AccountNameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_view_AccountNameResponse_descriptor,
        new java.lang.String[] { "AccName", "AccAge", });
    internal_static_view_ContactsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_view_ContactsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_view_ContactsRequest_descriptor,
        new java.lang.String[] { "ContactGroup", });
    internal_static_view_ContactsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_view_ContactsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_view_ContactsResponse_descriptor,
        new java.lang.String[] { "ContactDetails", "ContactId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
