// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculations.proto

package ds.examples.calculations;

public interface addMoneyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculations.addMoneyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 addMoney = 1;</code>
   */
  int getAddMoney();
}
