// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculations.proto

package ds.examples.calculations;

public interface balanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculations.balanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userBalance = 1;</code>
   */
  int getUserBalance();
}
