// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculations.proto

package ds.examples.calculations;

public final class BankingServiceImpl {
  private BankingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calculations_addMoneyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calculations_addMoneyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calculations_balanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calculations_balanceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022calculations.proto\022\014calculations\"#\n\017ad" +
      "dMoneyRequest\022\020\n\010addMoney\030\001 \001(\005\"&\n\017balan" +
      "ceResponse\022\023\n\013userBalance\030\001 \001(\0052[\n\013BankS" +
      "ervice\022L\n\010addMoney\022\035.calculations.addMon" +
      "eyRequest\032\035.calculations.balanceResponse" +
      "\"\0000\001B0\n\030ds.examples.calculationsB\022Bankin" +
      "gServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_calculations_addMoneyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_calculations_addMoneyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calculations_addMoneyRequest_descriptor,
        new java.lang.String[] { "AddMoney", });
    internal_static_calculations_balanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_calculations_balanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calculations_balanceResponse_descriptor,
        new java.lang.String[] { "UserBalance", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
