// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package ds.examples.history;

public interface DisplayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:history.DisplayRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 transactionIdStart = 1;</code>
   */
  int getTransactionIdStart();

  /**
   * <code>int32 transactionIdEnd = 2;</code>
   */
  int getTransactionIdEnd();
}
