// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package ds.examples.history;

public interface DisplayResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:history.DisplayResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 transactionId = 1;</code>
   */
  int getTransactionId();

  /**
   * <code>float transactionAmount = 2;</code>
   */
  float getTransactionAmount();
}
