// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package ds.examples.history;

public interface RecentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:history.RecentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 transactionValue = 1;</code>
   */
  int getTransactionValue();
}
