// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package ds.examples.history;

public interface RecentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:history.RecentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numberId = 1;</code>
   */
  int getNumberId();
}
