// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package ds.examples.history;

public final class TransferServiceImpl {
  private TransferServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_history_DisplayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_history_DisplayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_history_DisplayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_history_DisplayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_history_RecentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_history_RecentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_history_RecentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_history_RecentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rhistory.proto\022\007history\"F\n\016DisplayReque" +
      "st\022\032\n\022transactionIdStart\030\001 \001(\005\022\030\n\020transa" +
      "ctionIdEnd\030\002 \001(\005\"C\n\017DisplayResponse\022\025\n\rt" +
      "ransactionId\030\001 \001(\005\022\031\n\021transactionAmount\030" +
      "\002 \001(\002\"!\n\rRecentRequest\022\020\n\010numberId\030\001 \001(\005" +
      "\"*\n\016RecentResponse\022\030\n\020transactionValue\030\001" +
      " \001(\0022\250\001\n\016HistoryService\022K\n\022displayTransa" +
      "ction\022\027.history.DisplayRequest\032\030.history" +
      ".DisplayResponse\"\0000\001\022I\n\022recentTransactio" +
      "ns\022\026.history.RecentRequest\032\027.history.Rec" +
      "entResponse\"\000(\001B,\n\023ds.examples.historyB\023" +
      "TransferServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_history_DisplayRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_history_DisplayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_history_DisplayRequest_descriptor,
        new java.lang.String[] { "TransactionIdStart", "TransactionIdEnd", });
    internal_static_history_DisplayResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_history_DisplayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_history_DisplayResponse_descriptor,
        new java.lang.String[] { "TransactionId", "TransactionAmount", });
    internal_static_history_RecentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_history_RecentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_history_RecentRequest_descriptor,
        new java.lang.String[] { "NumberId", });
    internal_static_history_RecentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_history_RecentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_history_RecentResponse_descriptor,
        new java.lang.String[] { "TransactionValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
