// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package ds.examples.transfers;

public interface DeductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transfers.DeductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 deductTotal = 1;</code>
   */
  int getDeductTotal();
}
