// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package ds.examples.transfers;

public interface DeductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transfers.DeductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 deductAmount = 1;</code>
   */
  int getDeductAmount();
}
