// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package ds.examples.transfers;

public interface DepositRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transfers.DepositRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 depositAmount = 1;</code>
   */
  int getDepositAmount();
}
