// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package ds.examples.transfers;

public interface DepositResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transfers.DepositResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 depositTotal = 1;</code>
   */
  int getDepositTotal();
}
