// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package ds.examples.transfers;

public final class TransferServiceImpl {
  private TransferServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transfers_DepositRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transfers_DepositRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transfers_DepositResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transfers_DepositResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transfers_DeductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transfers_DeductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transfers_DeductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transfers_DeductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016transfer.proto\022\ttransfers\"\'\n\016DepositRe" +
      "quest\022\025\n\rdepositAmount\030\001 \001(\005\"\'\n\017DepositR" +
      "esponse\022\024\n\014depositTotal\030\001 \001(\005\"%\n\rDeductR" +
      "equest\022\024\n\014deductAmount\030\001 \001(\005\"%\n\016DeductRe" +
      "sponse\022\023\n\013deductTotal\030\001 \001(\0052\246\001\n\017Transfer" +
      "Service\022I\n\014depositFunds\022\031.transfers.Depo" +
      "sitRequest\032\032.transfers.DepositResponse\"\000" +
      "(\001\022H\n\013deductFunds\022\030.transfers.DeductRequ" +
      "est\032\031.transfers.DeductResponse\"\000(\0010\001B.\n\025" +
      "ds.examples.transfersB\023TransferServiceIm" +
      "plP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_transfers_DepositRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transfers_DepositRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transfers_DepositRequest_descriptor,
        new java.lang.String[] { "DepositAmount", });
    internal_static_transfers_DepositResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_transfers_DepositResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transfers_DepositResponse_descriptor,
        new java.lang.String[] { "DepositTotal", });
    internal_static_transfers_DeductRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_transfers_DeductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transfers_DeductRequest_descriptor,
        new java.lang.String[] { "DeductAmount", });
    internal_static_transfers_DeductResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_transfers_DeductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transfers_DeductResponse_descriptor,
        new java.lang.String[] { "DeductTotal", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
